create table Users (
	Id INT IDENTITY PRIMARY KEY,
	FullName NVARCHAR(100) NOT NULL,
	EMAIL NVARCHAR(100) NOT NULL UNIQUE,
	PasswordHash NVARCHAR(500) NOT NULL,
	PhoneNumber NVARCHAR(15),
	RoleId INT NOT NULL,
	CreatedAt DATETIME DEFAULT GETDATE()
);
GO
CREATE TABLE Roles(
	Id INT IDENTITY PRIMARY KEY,
	RoleName NVARCHAR(25) NOT NULL,
);
GO

CREATE TABLE Categories (
	Id INT IDENTITY PRIMARY KEY,
	Name NVARCHAR(100) NOT NULL,
	IsActive BIT DEFAULT 1
);
GO

CREATE TABLE Products (
	Id INT IDENTITY PRIMARY KEY,
	Name NVARCHAR(150) NOT NULL,
	Description NVARCHAR(500),
	Price DECIMAL(10,2) NOT NULL,
	IsEggless BIT DEFAULT 0,
	ImageURL NVARCHAR(550),
	CategoryId INT NOT NULL,
	IsAvailable BIT DEFAULT 1,
	CreatedAt DATETIME DEFAULT GETDATE(),
	FOREIGN KEY (CategoryId) REFERENCES Categories(Id)
);
GO

CREATE TABLE CartItems (
	Id INT IDENTITY PRIMARY KEY,
	UserId INT NOT NULL,
	ProductId INT NOT NULL,
	Quantity INT NOT NULL,
	AddedAt DATETIME DEFAULT GETDATE(),
	FOREIGN KEY (UserId) REFERENCES Users(Id),
	FOREIGN KEY (ProductId) REFERENCES Products(Id)
);
GO

CREATE TABLE Orders (
	Id INT IDENTITY PRIMARY KEY,
	UserId INT NOT NULL,
	TotalAmount DECIMAL(10,2) NOT NULL,
	OrderStatus NVARCHAR(50) DEFAULT 'Placed',
	CreatedAt DATETIME DEFAULT GETDATE(),
	FOREIGN KEY (UserId) REFERENCES Users(Id)
);
GO

CREATE TABLE OrderItems (
	Id INT IDENTITY PRIMARY KEY,
	OrderId INT NOT NULL,
	ProductId INT NOT NULL,
	Quantity INT NOT NULL,
	Price DECIMAL(10,2) NOT NULL,
	FOREIGN KEY (OrderId) REFERENCES Orders(Id),
	FOREIGN KEY (ProductId) REFERENCES Products(Id)
);
GO

CREATE TABLE Payments(
	Id INT IDENTITY PRIMARY KEY,
	OrderId INT NOT NULL,
	PaymentMethod NVARCHAR(50),
	PaymentStatus NVARCHAR(50),
	TransactionId NVARCHAR(100),
	PaidAt DATETIME DEFAULT GETDATE(),
	FOREIGN KEY (OrderId) REFERENCES Orders(Id)
);


